<a href="https://colab.research.google.com/github/habilg/keras_advanced/blob/master/keras_for_researchers_01_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
x=tf.constant([[1,2],[3,4]])

In [ ]:
x.shape

TensorShape([2, 2])

In [ ]:
x.dtype

tf.int32

In [ ]:
x.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [ ]:
x=tf.Variable([[1,2],[3,4]])

In [ ]:
np_arr=np.array([[5,6],[7,8]])
y=tf.Variable(np_arr)

In [ ]:
z=tf.ones(shape=(2,3)) #zeros
z

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
random_uniform=tf.random.uniform(shape=(2,3),minval=0,maxval=1)
random_uniform

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.9452318 , 0.03455603, 0.5051671 ],
       [0.5030968 , 0.52672195, 0.19076169]], dtype=float32)>

In [ ]:
random_normal = tf.random.normal(shape=(2,3),mean=0,stddev=1) #gamma,poison
random_normal

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.30780753, -1.1121861 ,  0.13558385],
       [-0.400321  , -1.165175  ,  1.0382717 ]], dtype=float32)>

# Indexing and Slicing

In [ ]:
random_normal[0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.30780753, -1.1121861 ,  0.13558385], dtype=float32)>

In [ ]:
random_normal[0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=0.30780753>

In [ ]:
random_normal[-1,-1]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0382717>

In [ ]:
random_normal[:,1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.48910946, -1.6059475 ], dtype=float32)>

# Tensor Manipulation
assign value  
reshape  
expand dimentions  
squeeze  
Flatten  
concatenate  
stack  



## assign a value

In [ ]:
a= tf.Variable([[3,4,8],[1,7,2]])
a

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[3, 4, 8],
       [1, 7, 2]], dtype=int32)>

In [ ]:
a[0,0].assign(100)
a

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[100,   4,   8],
       [  1,   7,   2]], dtype=int32)>

In [ ]:
a[0].assign(10)
a

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 10, 10],
       [ 1,  7,  2]], dtype=int32)>

In [ ]:
a[:,1].assign(0)
a

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10,  0, 10],
       [ 1,  0,  2]], dtype=int32)>

## reshape 

In [ ]:
a=tf.constant([3,4,8,1,7,2]) #define a tensor of shape [6]
b=tf.constant([[7,8,9,10],[4,5,6,7]]) #define a tensor of shape [2,4]
aNew=tf.reshape(a, [2,3])
aNew

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 4, 8],
       [1, 7, 2]], dtype=int32)>

In [ ]:
bNew=tf.reshape(b, [4,2]) #store the output in new tensors
bNew

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [ 4,  5],
       [ 6,  7]], dtype=int32)>

### Flatten

In [ ]:
aFlatten=tf.reshape(aNew,[-1])
aFlatten.numpy()

array([3, 4, 8, 1, 7, 2], dtype=int32)

In [ ]:
bFlatten=tf.reshape(bNew,[-1])
bFlatten.numpy()

array([ 7,  8,  9, 10,  4,  5,  6,  7], dtype=int32)

## Dimention expansion

In [ ]:
tf.expand_dims(a,0) #for batch

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[3, 4, 8, 1, 7, 2]], dtype=int32)>

In [ ]:
b_expand_dim=tf.expand_dims(b,0)
b_expand_dim.numpy()

array([[[ 7,  8,  9, 10],
        [ 4,  5,  6,  7]]], dtype=int32)

In [ ]:
b_expand_dim.shape

TensorShape([1, 2, 4])

In [ ]:
b_expanded_negative=tf.expand_dims(b,-1)
b_expanded_negative.numpy()

array([[[ 7],
        [ 8],
        [ 9],
        [10]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]]], dtype=int32)

In [ ]:
b_expanded_negative.shape

TensorShape([2, 4, 1])

In [ ]:
b_squeezed=tf.squeeze(b_expanded_negative)
b_squeezed.shape

TensorShape([2, 4])

## Concatenation

In [ ]:
a1=tf.random.uniform(shape=(4,4,3),minval=0,maxval=100,dtype=tf.int32)
a1

<tf.Tensor: shape=(4, 4, 3), dtype=int32, numpy=
array([[[75,  5, 86],
        [24, 36,  4],
        [ 9, 51, 19],
        [48, 51, 50]],

       [[92, 72, 84],
        [85, 54, 22],
        [42, 15, 95],
        [38, 55, 68]],

       [[23, 28, 66],
        [91,  2, 21],
        [11, 55, 19],
        [78, 92, 76]],

       [[32, 70, 33],
        [14, 57, 30],
        [43, 39, 36],
        [36, 57, 61]]], dtype=int32)>

In [ ]:
a1_0=a1[:,:,0]
a1_0

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[75, 24,  9, 48],
       [92, 85, 42, 38],
       [23, 91, 11, 78],
       [32, 14, 43, 36]], dtype=int32)>

In [ ]:
a1_1=a1[:,:,1]
a1_1

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 5, 36, 51, 51],
       [72, 54, 15, 55],
       [28,  2, 55, 92],
       [70, 57, 39, 57]], dtype=int32)>

In [ ]:
a1_2=a1[:,:,2]
a1_2

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[86,  4, 19, 50],
       [84, 22, 95, 68],
       [66, 21, 19, 76],
       [33, 30, 36, 61]], dtype=int32)>

In [ ]:
a1_concat_0=tf.concat([a1_0,a1_1,a1_2],0) #0-> rows
a1_concat_0.shape

TensorShape([12, 4])

In [ ]:
a1_concat_0

<tf.Tensor: shape=(12, 4), dtype=int32, numpy=
array([[75, 24,  9, 48],
       [92, 85, 42, 38],
       [23, 91, 11, 78],
       [32, 14, 43, 36],
       [ 5, 36, 51, 51],
       [72, 54, 15, 55],
       [28,  2, 55, 92],
       [70, 57, 39, 57],
       [86,  4, 19, 50],
       [84, 22, 95, 68],
       [66, 21, 19, 76],
       [33, 30, 36, 61]], dtype=int32)>

In [ ]:
a1_concat_1=tf.concat([a1_0,a1_1,a1_2],1) #1 -> cols
a1_concat_1.shape

TensorShape([4, 12])

In [ ]:
a1_concat_1

<tf.Tensor: shape=(4, 12), dtype=int32, numpy=
array([[75, 24,  9, 48,  5, 36, 51, 51, 86,  4, 19, 50],
       [92, 85, 42, 38, 72, 54, 15, 55, 84, 22, 95, 68],
       [23, 91, 11, 78, 28,  2, 55, 92, 66, 21, 19, 76],
       [32, 14, 43, 36, 70, 57, 39, 57, 33, 30, 36, 61]], dtype=int32)>

## Stacking

In [ ]:
a1_stack_0=tf.stack([a1_0,a1_1,a1_2],0) #0
a1_stack_0.shape

TensorShape([3, 4, 4])

In [ ]:
a1_stack_0[0]

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[75, 24,  9, 48],
       [92, 85, 42, 38],
       [23, 91, 11, 78],
       [32, 14, 43, 36]], dtype=int32)>

In [ ]:
a1_stack_1=tf.stack([a1_0,a1_1,a1_2],1) #1
a1_stack_1.shape

TensorShape([4, 3, 4])

In [ ]:
a1_stack_1[0]

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[75, 24,  9, 48],
       [ 5, 36, 51, 51],
       [86,  4, 19, 50]], dtype=int32)>

In [ ]:
a1_stack_2=tf.stack([a1_0,a1_1,a1_2],2) #2 or -1
a1_stack_2.shape

TensorShape([4, 4, 3])

In [ ]:
a1_stack_2[0]

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[75,  5, 86],
       [24, 36,  4],
       [ 9, 51, 19],
       [48, 51, 50]], dtype=int32)>

# Math
reduce  
elementwise sum  
elementwise multiply  
matrix multiply   

In [ ]:
a= tf.Variable([[3,4,8],[1,7,2]])


In [ ]:
tf.reduce_min(a,axis=0) #max

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 2], dtype=int32)>

In [ ]:
tf.reduce_min(a,axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 1], dtype=int32)>

In [ ]:
tf.reduce_sum(a,axis=0) #mean #prod

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 11, 10], dtype=int32)>

In [ ]:
tf.reduce_sum(a,axis=0, keepdims=True)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[ 4, 11, 10]], dtype=int32)>

In [ ]:
a= tf.Variable([[3,4],[1,7]])
b=tf.Variable([[3,6],[2,7]])

In [ ]:
a+b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6, 10],
       [ 3, 14]], dtype=int32)>

In [ ]:
tf.add(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6, 10],
       [ 3, 14]], dtype=int32)>

In [ ]:
a+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 14],
       [11, 17]], dtype=int32)>

In [ ]:
a@b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 46],
       [17, 55]], dtype=int32)>

In [ ]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 46],
       [17, 55]], dtype=int32)>

In [ ]:
a*b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 24],
       [ 2, 49]], dtype=int32)>

In [ ]:
tf.multiply(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 24],
       [ 2, 49]], dtype=int32)>